/**
 * data.js — single source of truth for categories + items.
 *
 * This is the ONLY place you edit to add/remove/change content.
 * - index.html reads this file directly (as a <script> tag) to render
 *   the sidebar and item grid.
 * - generate_items.js reads this same object (via Node's require) to
 *   (re)generate the static detail pages under items/*.html.
 *
 * Schema:
 * {
 *   id: string            // unique category id, used as URL-safe slug
 *   label: string          // sidebar label (Korean)
 *   icon: string           // key into ICONS in icons.js
 *   description: string    // shown under the category title in the main pane
 *   items: [
 *     {
 *       id: string         // unique item id -> items/{id}.html
 *       title: string
 *       meta: string       // small caption line shown on the card (code)
 *       body: string       // paragraph(s) shown on the detail page (\n\n = new paragraph)
 *       hue: number         // 0-360, drives the placeholder "cover art" gradient
 *       skipGenerate: bool  // optional — true if items/{id}.html is hand-written
 *     }, ...
 *   ]
 * }
 *
 * NOTE ON CONTENT: most `body` fields below are short placeholders on
 * purpose — the real write-ups will be dropped in later as finished
 * items/{id}.html pages. This file's job right now is just to lock in the
 * category/item STRUCTURE (ids, labels, ordering) so the site is
 * navigable while content is filled in incrementally.
 */
/**
 * PORTAL_TOOLS — the 12 tiles shown on the main portal (default landing view
 * and whatever appears when the "AI NATIVE WORLD" logo is clicked).
 * This is purely decorative/branding content: clicking a tile does nothing.
 * Category browsing is done exclusively through the sidebar.
 *
 * icon: filename inside assets/portal/
 * bg:   CSS background for the rounded tile
 */
const PORTAL_TOOLS = [
  { label: "ChatGPT", icon: "icon-chatgpt.png", bg: "#ffffff" },
  { label: "Claude", icon: "icon-claude.png", bg: "#d97757" },
  { label: "Claude Code", icon: "icon-claudecode.png", bg: "#141414" },
  { label: "NotebookLM", icon: "icon-notebooklm.png", bg: "#6c5ce7" },
  { label: "Suno", icon: "icon-suno.png", bg: "#ff7a59" },
  { label: "Nano Banana", icon: "icon-nanobanana.png", bg: "#1a1a1e" },
  { label: "Claude Cowork", icon: "icon-claude.png", bg: "#e8734a" },
  { label: "Claude Design", icon: "icon-claude.png", bg: "#141414" },
  { label: "ElevenLabs", icon: "icon-elevenlabs.png", bg: "#141414" },
  { label: "Replit", icon: "icon-replit.png", bg: "#141414" },
  { label: "CapCut", icon: "icon-capcut.png", bg: "#141414" },
  { label: "Higgsfield", icon: "icon-higgsfield.png", bg: "#1e8449" },
];

/**
 * MODALITY_GROUPS — the 6 "modality" cards shown on the main portal, just
 * below the PORTAL_TOOLS grid. Each group bundles the best tool(s) for one
 * data modality (chat, research, image, code, video, audio).
 *
 * tools[].icon: filename inside assets/portal/ (reuses the same icon set
 * as PORTAL_TOOLS above, so bg colors are kept consistent).
 */
const MODALITY_GROUPS = [
  {
    label: "대화 · 채팅",
    icon: "message-circle",
    tools: [
      { icon: "icon-chatgpt.png", bg: "#ffffff" },
      { icon: "icon-claude.png", bg: "#d97757" },
    ],
    desc: "ChatGPT · Claude — 모든 일의 출발점.",
  },
  {
    label: "리서치",
    icon: "device",
    tools: [{ icon: "icon-notebooklm.png", bg: "#6c5ce7" }],
    desc: "NotebookLM — 자료 더미를 인사이트로.",
  },
  {
    label: "이미지 · 디자인",
    icon: "image",
    tools: [
      { icon: "icon-claude.png", bg: "#141414" },
      { icon: "icon-nanobanana.png", bg: "#1a1a1e" },
    ],
    desc: "Claude Design · Nano Banana — 브랜드 자산을 직접.",
  },
  {
    label: "코드 · 빌드",
    icon: "code",
    tools: [
      { icon: "icon-claudecode.png", bg: "#141414" },
      { icon: "icon-replit.png", bg: "#141414" },
    ],
    desc: "Claude Code · Replit — 비개발자도 앱을 띄웁니다.",
  },
  {
    label: "영상",
    icon: "video",
    tools: [
      { icon: "icon-higgsfield.png", bg: "#1e8449" },
      { icon: "icon-capcut.png", bg: "#141414" },
    ],
    desc: "Higgsfield · CapCut — 광고와 숏폼을 한 자리에서.",
  },
  {
    label: "오디오 · 보이스",
    icon: "music",
    tools: [
      { icon: "icon-suno.png", bg: "#ff7a59" },
      { icon: "icon-elevenlabs.png", bg: "#141414" },
    ],
    desc: "Suno · ElevenLabs — BGM부터 더빙까지.",
  },
];


/**
 * LATEST_POSTS — 메인 포털 맨 아래 "최신 글" 카드 3장.
 * 새 글을 올렸으면 이 배열 맨 앞에 한 줄 추가하고 마지막 줄을 지우면 됩니다.
 * cat/item 은 CATEGORIES의 id를 가리키며, 제목과 링크는 거기서 자동으로 가져옵니다.
 * summary 를 비워두면 해당 항목의 body 첫 문장이 쓰입니다.
 */
const LATEST_POSTS = [
  { cat: "e00", item: "e09", date: "2026년 8월 24일",
    summary: "screen, git, Postman으로 AI 서버를 운영하며 쓰는 관리 꿀팁을 정리했습니다." },
  { cat: "h00", item: "h02", date: "2026년 8월 18일",
    summary: "Supabase로 데이터베이스를 처음 붙여보는 초보 개발자용 시작 가이드." },
  { cat: "d02", item: "d24", date: "2026년 9월 18일",
    summary: "클로드 코드를 실전에서 200% 활용하는 28가지 완벽 가이드를 정리했습니다." },
];


const CATEGORIES = [
  {
    id: "a00",
    folder: "A_AI_Basic",
    label: "AI Basic",
    icon: "file-text",
    description: "AI를 처음 시작하는 사람을 위한 핵심 개념 — 용어, LLM 동작 원리, 멀티모달, RLHF, 파인튜닝부터 RAG·에이전트·AGI까지.",
    items: [
      { id: "a01", title: "신입 AI 키우기 — AI 용어 12개로 배우는 성장 로드맵", meta: "A01", hue: 205, skipGenerate: true,
        body: "신입 AI 키우기 — AI 용어 12개로 배우는 성장 로드맵." },
      { id: "a02", title: "LLM의 동작 원리 — 토큰화에서 다음 토큰 예측까지", meta: "A02", hue: 205, skipGenerate: true,
        body: "LLM의 동작 원리 — 토큰화에서 다음 토큰 예측까지." },
      { id: "a03", title: "멀티모달(Multi-Modal) AI — 텍스트를 넘어, 보고 듣는 지능으로", meta: "A03", hue: 205, skipGenerate: true,
        body: "멀티모달(Multi-Modal) AI — 텍스트를 넘어, 보고 듣는 지능으로." },
      { id: "a04", title: "RLHF (Reinforcement Learning from Human Feedback) 완벽 가이드", meta: "A04", hue: 205, skipGenerate: true,
        body: "RLHF (Reinforcement Learning from Human Feedback) 완벽 가이드." },
      { id: "a05", title: "파인튜닝 (Fine-Tuning) 완벽 가이드", meta: "A05", hue: 205, skipGenerate: true,
        body: "파인튜닝 (Fine-Tuning) 완벽 가이드." },
      { id: "a06", title: "프롬프트 엔지니어링이란 무엇인가 — 개념, 배경, LLM 핵심 파라미터", meta: "A06", hue: 205, skipGenerate: true,
        body: "프롬프트 엔지니어링이란 무엇인가 — 개념, 배경, LLM 핵심 파라미터." },
      { id: "a07", title: "지식베이스 (Knowledge Base) 완벽 가이드", meta: "A07", hue: 205, skipGenerate: true,
        body: "지식베이스 (Knowledge Base) 완벽 가이드." },
      { id: "a08a", title: "RAG(Retrieval-Augmented Generation)란 — 개념, Fine-tuning 차이, 검색 기법", meta: "A08A", hue: 205, skipGenerate: true,
        body: "RAG(Retrieval-Augmented Generation)란 — 개념, Fine-tuning 차이, 검색 기법." },
      { id: "a08b", title: "RAG의 시작, 데이터 파이프라인 — LlamaParse, Semantic Chunking", meta: "A08B", hue: 205, skipGenerate: true,
        body: "RAG의 시작, 데이터 파이프라인 — LlamaParse, Semantic Chunking." },
      { id: "a08c", title: "RAG를 위한 Embedding Model 선정, Vector DB 구축", meta: "A08C", hue: 205, skipGenerate: true,
        body: "RAG를 위한 Embedding Model 선정, Vector DB 구축." },
      { id: "a08d", title: "RAG 고급 검색 기술 총정리 — RRF, KG-RAG, ColBERT 등", meta: "A08D", hue: 205, skipGenerate: true,
        body: "RAG 고급 검색 기술 총정리 — RRF, KG-RAG, ColBERT 등." },
      { id: "a08e", title: "에이전틱 RAG (Agentic RAG) 완벽 가이드 — 정의, 구성요소, 특징 및 장단점, 활용분야, 실습", meta: "A08E", hue: 205, skipGenerate: true,
        body: "에이전틱 RAG (Agentic RAG) 완벽 가이드 — 정의, 구성요소, 특징 및 장단점, 활용분야, 실습." },
      { id: "a09", title: "MCP (Model Context Protocol)란 무엇인가 — 정의, 아키텍처, 장단점, 활용 분야, 실습", meta: "A09", hue: 205, skipGenerate: true,
        body: "MCP (Model Context Protocol)란 무엇인가 — 정의, 아키텍처, 장단점, 활용 분야, 실습." },
      { id: "a10a", title: "Complete Agentic AI Course — 완벽 요약 리포트", meta: "A10A", hue: 205, skipGenerate: true,
        body: "Complete Agentic AI Course — 완벽 요약 리포트." },
      { id: "a10b", title: "AI Agent(에이전트)란 무엇인가 — 정의, 구성요소, 유형, 장단점, 주요 활용 분야, 실습", meta: "A10B", hue: 205, skipGenerate: true,
        body: "AI Agent(에이전트)란 무엇인가 — 정의, 구성요소, 유형, 장단점, 주요 활용 분야, 실습." },
      { id: "a10c", title: "AI Agent와 Agentic AI의 차이 완벽 정리 — 정의, 특징 및 장단점, 활용 분야, 실습", meta: "A10C", hue: 205, skipGenerate: true,
        body: "AI Agent와 Agentic AI의 차이 완벽 정리 — 정의, 특징 및 장단점, 활용 분야, 실습." },
      { id: "a10d", title: "AI Agent의 핵심 무기 Tool Calling(도구 호출) 완벽 가이드 — 정의, 구성요소, 장단점, 실습", meta: "A10D", hue: 205, skipGenerate: true,
        body: "AI Agent의 핵심 무기 Tool Calling(도구 호출) 완벽 가이드 — 정의, 구성요소, 장단점, 실습." },
      { id: "a10e", title: "에이전틱 AI 구축 기초 — 강의별 실습 프롬프트 모음", meta: "A10E", hue: 205, skipGenerate: true,
        body: "에이전틱 AI 구축 기초 — 강의별 실습 프롬프트 모음." },
      { id: "a11", title: "워크플로우 자동화 (Workflow Automation) 완벽 가이드", meta: "A11", hue: 205, skipGenerate: true,
        body: "워크플로우 자동화 (Workflow Automation) 완벽 가이드." },
      { id: "a12", title: "하네스 엔지니어링(Harness Engineering)이란 — 정의, 구성요소, 특징 및 장단점, 실습", meta: "A12", hue: 205, skipGenerate: true,
        body: "하네스 엔지니어링(Harness Engineering)이란 — 정의, 구성요소, 특징 및 장단점, 실습." },
      { id: "a13", title: "AI 지능 수준 분류: ANI, AGI, ASI 완벽 가이드", meta: "A13", hue: 205, skipGenerate: true,
        body: "AI 지능 수준 분류: ANI, AGI, ASI 완벽 가이드." },
    ],
  },
  {
    id: "b00",
    folder: "B_AI_Advanced_1",
    label: "AI Advanced#1",
    icon: "zap",
    description: "AI 발전 역사와 프롬프트·컨텍스트·루프·그래프 엔지니어링, 오케스트레이션, LangChain/LangGraph, 그리고 헷갈리는 개념 비교 모음.",
    items: [
      { id: "b01", title: "AI 발전흐름 — 프롬프트에서 그래프 엔지니어링까지", meta: "B01", hue: 255, skipGenerate: true,
        body: "AI 발전흐름 — 프롬프트에서 그래프 엔지니어링까지." },
      { id: "b02a", title: "프롬프트 엔지니어링이란 무엇인가 — 개념, 배경, LLM 핵심 파라미터", meta: "B02A", hue: 255, skipGenerate: true,
        body: "프롬프트 엔지니어링이란 무엇인가 — 개념, 배경, LLM 핵심 파라미터." },
      { id: "b02b", title: "프롬프트 엔지니어링 실전 설계 꿀팁 1 — 4가지 국룰과 5대 기본 작업", meta: "B02B", hue: 255, skipGenerate: true,
        body: "프롬프트 엔지니어링 실전 설계 꿀팁 1 — 4가지 국룰과 5대 기본 작업." },
      { id: "b02c", title: "프롬프트 엔지니어링 실전 설계 꿀팁 2 — Few-Shot, CoT, Self-Consistency", meta: "B02C", hue: 255, skipGenerate: true,
        body: "프롬프트 엔지니어링 실전 설계 꿀팁 2 — Few-Shot, CoT, Self-Consistency." },
      { id: "b02d", title: "프롬프트 엔지니어링 실전 설계 꿀팁 3 — RAG, ReAct, ToT, PAL, Reflexion", meta: "B02D", hue: 255, skipGenerate: true,
        body: "프롬프트 엔지니어링 실전 설계 꿀팁 3 — RAG, ReAct, ToT, PAL, Reflexion." },
      { id: "b02e", title: "프롬프트 엔지니어링 실전 설계 꿀팁 4 — Data Generation, Function Calling, Agent", meta: "B02E", hue: 255, skipGenerate: true,
        body: "프롬프트 엔지니어링 실전 설계 꿀팁 4 — Data Generation, Function Calling, Agent." },
      { id: "b02f", title: "Prompt Injection이란 무엇인가 — 개요, 정의, 특징, 기법, 실습, 보안 가이드", meta: "B02F", hue: 255, skipGenerate: true,
        body: "Prompt Injection이란 무엇인가 — 개요, 정의, 특징, 기법, 실습, 보안 가이드." },
      { id: "b02g", title: "프롬프트 마스터: ReAct (추론과 행동) vs CoT (생각의 사슬) 기법 비교", meta: "B02G", hue: 255, skipGenerate: true,
        body: "프롬프트 마스터: ReAct (추론과 행동) vs CoT (생각의 사슬) 기법 비교." },
      { id: "b03", title: "컨텍스트 엔지니어링(Context Engineering) 완벽 가이드 — 정의, 구성요소, 특징 및 장단점, 실습", meta: "B03", hue: 255, skipGenerate: true,
        body: "컨텍스트 엔지니어링(Context Engineering) 완벽 가이드 — 정의, 구성요소, 특징 및 장단점, 실습." },
      { id: "b04", title: "루프 엔지니어링(Loop Engineering)에 대해 자세히 알아보자! — 개요 및 정의, 구성요소, 특징 및 장단점, 구축", meta: "B04", hue: 255, skipGenerate: true,
        body: "루프 엔지니어링(Loop Engineering)에 대해 자세히 알아보자! — 개요 및 정의, 구성요소, 특징 및 장단점, 구축." },
      { id: "b05", title: "그래프 엔지니어링 — AI 시스템 설계의 진화와 구조적 최적화", meta: "B05", hue: 255, skipGenerate: true,
        body: "그래프 엔지니어링 — AI 시스템 설계의 진화와 구조적 최적화." },
      { id: "b06", title: "LLM 오케스트레이션(Orchestration)이란 무엇인가 — 정의, 구성요소, 장단점, 실습", meta: "B06", hue: 255, skipGenerate: true,
        body: "LLM 오케스트레이션(Orchestration)이란 무엇인가 — 정의, 구성요소, 장단점, 실습." },
      { id: "b07", title: "LangChain v1.0 — AI 에이전트 아키텍처 마스터클래스", meta: "B07", hue: 255, skipGenerate: true,
        body: "LangChain v1.0 — AI 에이전트 아키텍처 마스터클래스." },
      { id: "b08a", title: "Claude Skills vs Subagent 완벽 가이드", meta: "B08A", hue: 255, skipGenerate: true,
        body: "Claude Skills vs Subagent 완벽 가이드." },
      { id: "b08b", title: "CLAUDE.md vs Skill 완벽 비교 가이드", meta: "B08B", hue: 255, skipGenerate: true,
        body: "CLAUDE.md vs Skill 완벽 비교 가이드." },
      { id: "b08c", title: "CLAUDE.md vs .claude/rules/ vs Skill 완벽 비교 가이드", meta: "B08C", hue: 255, skipGenerate: true,
        body: "CLAUDE.md vs .claude/rules/ vs Skill 완벽 비교 가이드." },
      { id: "b08d", title: "Subagent vs Agent team 완벽 비교 가이드", meta: "B08D", hue: 255, skipGenerate: true,
        body: "Subagent vs Agent team 완벽 비교 가이드." },
      { id: "b08e", title: "MCP vs Skill 완벽 비교 가이드", meta: "B08E", hue: 255, skipGenerate: true,
        body: "MCP vs Skill 완벽 비교 가이드." },
      { id: "b08f", title: "Hook vs Skill 완벽 비교 가이드", meta: "B08F", hue: 255, skipGenerate: true,
        body: "Hook vs Skill 완벽 비교 가이드." },
      { id: "b08g", title: "프롬프트 · 스킬 · 에이전트 — 무엇이 다르고 왜 나눠졌나", meta: "B08G", hue: 255, skipGenerate: true,
        body: "프롬프트 · 스킬 · 에이전트 — 무엇이 다르고 왜 나눠졌나." },
    ],
  },
  {
    id: "c00",
    folder: "C_AI_Advanced_2",
    label: "AI Advanced#2",
    icon: "cpu",
    description: "영상관련기술, 온톨로지, On-Premise/On-Device LLM, 추론(Reasoning), 자연어이해, 임베딩·Vector DB까지 더 깊은 AI 기초 이론.",
    items: [
      { id: "c01", title: "이미지 와핑(Image Warping)에 대해 자세히 알아보자! — 정의, 구성요소, 장단점, 실습", meta: "C01", hue: 265, skipGenerate: true,
        body: "이미지 와핑(Image Warping)에 대해 자세히 알아보자! — 정의, 구성요소, 장단점, 실습." },
      { id: "c02a", title: "온톨로지(Ontology)란 무엇인가 — 정의, 구성요소, 장단점, 활용 분야, 실습", meta: "C02A", hue: 265, skipGenerate: true,
        body: "온톨로지(Ontology)란 무엇인가 — 정의, 구성요소, 장단점, 활용 분야, 실습." },
      { id: "c02b", title: "브리핑: 기업 생성형 AI 도입의 핵심 성공 동력 — 온톨로지(Ontology) 프로젝트 분석", meta: "C02B", hue: 265, skipGenerate: true,
        body: "브리핑: 기업 생성형 AI 도입의 핵심 성공 동력 — 온톨로지(Ontology) 프로젝트 분석." },
      { id: "c03a", title: "온프레미스 AI(On-premise AI) 완벽 가이드", meta: "C03A", hue: 265, skipGenerate: true,
        body: "온프레미스 AI(On-premise AI) 완벽 가이드." },
      { id: "c03b", title: "Docker + vLLM으로 Gemma4 31B 모델 서빙하기", meta: "C03B", hue: 265, skipGenerate: true,
        body: "Docker + vLLM으로 Gemma4 31B 모델 서빙하기." },
      { id: "c03c", title: "Docker로 vLLM 모델 서빙 및 서버 구축 A to Z", meta: "C03C", hue: 265, skipGenerate: true,
        body: "Docker로 vLLM 모델 서빙 및 서버 구축 A to Z." },
      { id: "c03d", title: "Docker: AI 개발을 위한 Docker 완벽 가이드", meta: "C03D", hue: 265, skipGenerate: true,
        body: "Docker: AI 개발을 위한 Docker 완벽 가이드." },
      { id: "c04", title: "온디바이스 AI(On-Device AI)에 대해 자세히 알아보자", meta: "C04", hue: 265, skipGenerate: true,
        body: "온디바이스 AI(On-Device AI)에 대해 자세히 알아보자." },
      { id: "c05", title: "Inference와 Reasoning(추론) 완벽 가이드", meta: "C05", hue: 265, skipGenerate: true,
        body: "Inference와 Reasoning(추론) 완벽 가이드." },
      { id: "c06a", title: "NLP(자연어 처리)란 무엇인가", meta: "C06A", hue: 265, skipGenerate: true,
        body: "NLP(자연어 처리)란 무엇인가." },
      { id: "c06b", title: "자연어 이해(NLU)란 무엇일까", meta: "C06B", hue: 265, skipGenerate: true,
        body: "자연어 이해(NLU)란 무엇일까." },
      { id: "c06c", title: "ASR(자동 음성 인식)이란 무엇인가", meta: "C06C", hue: 265, skipGenerate: true,
        body: "ASR(자동 음성 인식)이란 무엇인가." },
      { id: "c07a", title: "임베딩(Embedding)이란 — 정의, 발전 과정, 최신 트렌드", meta: "C07A", hue: 265, skipGenerate: true,
        body: "임베딩(Embedding)이란 — 정의, 발전 과정, 최신 트렌드." },
      { id: "c07b", title: "최신 임베딩 모델과 원리 — BERT, OpenAI, MTEB, 거리 계산", meta: "C07B", hue: 265, skipGenerate: true,
        body: "최신 임베딩 모델과 원리 — BERT, OpenAI, MTEB, 거리 계산." },
      { id: "c07c", title: "Embedding 실습 및 Vector DB 맛보기 (OpenAI, ChromaDB)", meta: "C07C", hue: 265, skipGenerate: true,
        body: "Embedding 실습 및 Vector DB 맛보기 (OpenAI, ChromaDB)." },
    ],
  },
  {
    id: "d00",
    folder: "D1_AI_Tools-Introduction",
    label: "AI Tools",
    icon: "star",
    description: "대화형 AI, 리서치, 이미지·디자인, 코드 빌드, 영상·오디오, 자동화, 문서 생산성까지 — 지금 쓰는 AI 툴 총정리.",
    items: [
      { id: "d01a", title: "Chat AI Tools Full Comparison", meta: "D01A", hue: 30, skipGenerate: true,
        body: "Chat AI Tools Full Comparison." },
      { id: "d01b", title: "ChatGPT Gemini Claude Comparison", meta: "D01B", hue: 30, skipGenerate: true,
        body: "ChatGPT Gemini Claude Comparison." },
      { id: "d02a", title: "직장인이라면 꼭 알아야 할 무료 AI, NotebookLM 2.0 달라진 7가지", meta: "D02A", hue: 30, skipGenerate: true,
        body: "직장인이라면 꼭 알아야 할 무료 AI, NotebookLM 2.0 달라진 7가지." },
      { id: "d02b", title: "Perplexity AI 특장점 상세 정리", meta: "D02B", hue: 30, skipGenerate: true,
        body: "Perplexity AI 특장점 상세 정리." },
      { id: "d02c", title: "NotebookLM vs Perplexity 비교 분석", meta: "D02C", hue: 30, skipGenerate: true,
        body: "NotebookLM vs Perplexity 비교 분석." },
      { id: "d03a", title: "Claude Design 특장점 상세 분석", meta: "D03A", hue: 30, skipGenerate: true,
        body: "Claude Design 특장점 상세 분석." },
      { id: "d03b", title: "Nano Banana AI 특장점 상세 정리", meta: "D03B", hue: 30, skipGenerate: true,
        body: "Nano Banana AI 특장점 상세 정리." },
      { id: "d03c", title: "Nano Banana vs Claude Design 비교 분석", meta: "D03C", hue: 30, skipGenerate: true,
        body: "Nano Banana vs Claude Design 비교 분석." },
      { id: "d04", title: "코드 빌드 (Claude Code, Replit, Cursor) · 정보 허브", meta: "D04", hue: 30, skipGenerate: true,
        body: "코드 빌드 (Claude Code, Replit, Cursor) · 정보 허브." },
      { id: "d05", title: "영상 (Higgsfield, CapCut) · 정보 허브", meta: "D05", hue: 30, skipGenerate: true,
        body: "영상 (Higgsfield, CapCut) · 정보 허브." },
      { id: "d06", title: "오디오 보이스 (Suno, ElevenLabs) · 정보 허브", meta: "D06", hue: 30, skipGenerate: true,
        body: "오디오 보이스 (Suno, ElevenLabs) · 정보 허브." },
      { id: "d07", title: "자동화 에이전트 (n8n, Zapier, Make) · 정보 허브", meta: "D07", hue: 30, skipGenerate: true,
        body: "자동화 에이전트 (n8n, Zapier, Make) · 정보 허브." },
      { id: "d08", title: "문서 생산성 (Notion AI, Obsidian) · 정보 허브", meta: "D08", hue: 30, skipGenerate: true,
        body: "문서 생산성 (Notion AI, Obsidian) · 정보 허브." },
      { id: "d09", title: "AI Tool Reference Sites", meta: "D09", hue: 30, skipGenerate: true,
        body: "AI Tool Reference Sites." },
    ],
  },
  {
    id: "d01",
    folder: "D2_AI_Tools-Google",
    label: "AI Tools · Google",
    icon: "star",
    description: "구글의 무료 AI 도구 모음.",
    items: [
      { id: "d11", title: "최대 생산성을 위한 구글 필수 무료 AI 도구 7가지", meta: "D11", hue: 30, skipGenerate: true,
        body: "최대 생산성을 위한 구글 필수 무료 AI 도구 7가지." },
    ],
  },
  {
    id: "d02",
    folder: "D3_AI_Tools-Claude",
    label: "AI Tools · Claude",
    icon: "star",
    description: "Claude 활용법, 아티팩트, 클로드 코드 마스터 가이드 모음.",
    items: [
      { id: "d21", title: "Claude Intro — 기능·접근·데스크톱 앱·프로젝트·아티팩트·스킬·커넥터·Research", meta: "D21", hue: 30, skipGenerate: true,
        body: "Claude Intro — 기능·접근·데스크톱 앱·프로젝트·아티팩트·스킬·커넥터·Research." },
      { id: "d22", title: "Claude 아티팩트(Artifacts) 완전 매뉴얼", meta: "D22", hue: 30, skipGenerate: true,
        body: "Claude 아티팩트(Artifacts) 완전 매뉴얼." },
      { id: "d23", title: "클로드(Claude) 200% 활용법 기초 세팅 가이드", meta: "D23", hue: 30, skipGenerate: true,
        body: "클로드(Claude) 200% 활용법 기초 세팅 가이드." },
      { id: "d24", title: "클로드 코드 마스터하기 — 28가지 완벽 가이드", meta: "D24", hue: 30, skipGenerate: true,
        body: "클로드 코드 마스터하기 — 28가지 완벽 가이드." },
      { id: "d25", title: "클로드 코드 효율성 극대화 — 토큰 최적화와 비용 절감 가이드", meta: "D25", hue: 30, skipGenerate: true,
        body: "클로드 코드 효율성 극대화 — 토큰 최적화와 비용 절감 가이드." },
    ],
  },
  {
    id: "d03",
    folder: "D4_AI_Tools-ChatGPT",
    label: "AI Tools · ChatGPT",
    icon: "star",
    description: "ChatGPT 활용법 모음 (준비 중).",
    items: [
    ],
  },
  {
    id: "e00",
    folder: "E_Claude_Course",
    label: "Claude강좌",
    icon: "book-open",
    description: "Claude 제품 공식 강좌 모음 — Claude 101부터 Claude Code, MCP, Subagents, Agent Skills, AI-Native SDLC까지.",
    items: [
      { id: "e01", title: "Claude Intro — 기능·접근·데스크톱 앱·프로젝트·아티팩트·스킬·커넥터·Research", meta: "E01", hue: 15, skipGenerate: true,
        body: "Claude Intro — 기능·접근·데스크톱 앱·프로젝트·아티팩트·스킬·커넥터·Research." },
      { id: "e02", title: "Claude Code 101 — 에이전틱 루프·설치·워크플로우·컨텍스트·코드리뷰·커스터마이징", meta: "E02", hue: 15, skipGenerate: true,
        body: "Claude Code 101 — 에이전틱 루프·설치·워크플로우·컨텍스트·코드리뷰·커스터마이징." },
      { id: "e03", title: "Introduction to Claude Cowork — 설정·위임·컨텍스트·스킬/플러그인·확장·안전 습관", meta: "E03", hue: 15, skipGenerate: true,
        body: "Introduction to Claude Cowork — 설정·위임·컨텍스트·스킬/플러그인·확장·안전 습관." },
      { id: "e04", title: "Claude Platform 101 — API·모델선택·에이전트루프·툴·확장·매니지드 에이전트", meta: "E04", hue: 15, skipGenerate: true,
        body: "Claude Platform 101 — API·모델선택·에이전트루프·툴·확장·매니지드 에이전트." },
      { id: "e05", title: "Claude Code in Action — 조율·설정·자동화·검증", meta: "E05", hue: 15, skipGenerate: true,
        body: "Claude Code in Action — 조율·설정·자동화·검증." },
      { id: "e06", title: "Introduction to Model Context Protocol — 아키텍처·서버·클라이언트·통합", meta: "E06", hue: 15, skipGenerate: true,
        body: "Introduction to Model Context Protocol — 아키텍처·서버·클라이언트·통합." },
      { id: "e07", title: "Model Context Protocol: Advanced Topics — 샘플링·알림·Roots·전송 계층", meta: "E07", hue: 15, skipGenerate: true,
        body: "Model Context Protocol: Advanced Topics — 샘플링·알림·Roots·전송 계층." },
      { id: "e08", title: "Introduction to Subagents — 원리·생성·설계·활용", meta: "E08", hue: 15, skipGenerate: true,
        body: "Introduction to Subagents — 원리·생성·설계·활용." },
      { id: "e09", title: "The AI-Native SDLC Playbook — 6단계로 다시 그리는 소프트웨어 개발 라이프사이클", meta: "E09", hue: 15, skipGenerate: true,
        body: "The AI-Native SDLC Playbook — 6단계로 다시 그리는 소프트웨어 개발 라이프사이클." },
      { id: "e10", title: "Introduction to Agent Skills — 생성·설명작성·구조화·공유·문제해결", meta: "E10", hue: 15, skipGenerate: true,
        body: "Introduction to Agent Skills — 생성·설명작성·구조화·공유·문제해결." },
    ],
  },
  {
    id: "f00",
    folder: "F_AI_Fluency",
    label: "AI Fluency",
    icon: "message-circle",
    description: "AI Fluency 프레임워크와 AI 역량·한계, AI 활용 교육에 대한 강좌 요약.",
    items: [
      { id: "f01", title: "AI Fluency: Framework & Foundations — 강좌 요약", meta: "F01", hue: 340, skipGenerate: true,
        body: "AI Fluency: Framework & Foundations — 강좌 요약." },
      { id: "f02", title: "AI Capabilities and Limitations — 강좌 요약", meta: "F02", hue: 340, skipGenerate: true,
        body: "AI Capabilities and Limitations — 강좌 요약." },
      { id: "f03", title: "Teaching AI Fluency — 강좌 요약", meta: "F03", hue: 340, skipGenerate: true,
        body: "Teaching AI Fluency — 강좌 요약." },
    ],
  },
  {
    id: "g00",
    folder: "G_AI_Applications",
    label: "AI 활용",
    icon: "layers",
    description: "LLM Wiki, Graphify, 2nd Brain, 바이브코딩, Gemini+Playwright 등 AI를 실제 워크플로우에 적용하는 방법.",
    items: [
      { id: "g01a", title: "LLM Wiki 아키텍처 및 거버넌스 브리핑", meta: "G01A", hue: 190, skipGenerate: true,
        body: "LLM Wiki 아키텍처 및 거버넌스 브리핑." },
      { id: "g01b", title: "LLM Wiki 방식 비교 — Ar9av vs kytmanov vs domleca", meta: "G01B", hue: 190, skipGenerate: true,
        body: "LLM Wiki 방식 비교 — Ar9av vs kytmanov vs domleca." },
      { id: "g01c", title: "안드레 카파시의 'LLM Wiki' 완벽 정복 — Obsidian + Claude Code", meta: "G01C", hue: 190, skipGenerate: true,
        body: "안드레 카파시의 'LLM Wiki' 완벽 정복 — Obsidian + Claude Code." },
      { id: "g01d", title: "Obsidian LLM Wiki 만들기 — 초보자 설치부터 사용까지", meta: "G01D", hue: 190, skipGenerate: true,
        body: "Obsidian LLM Wiki 만들기 — 초보자 설치부터 사용까지." },
      { id: "g02", title: "Graphify Overview — 코드와 문서를 지식 그래프로", meta: "G02", hue: 190, skipGenerate: true,
        body: "Graphify Overview — 코드와 문서를 지식 그래프로." },
      { id: "g03a", title: "The Graphify Blueprint — LLM Wiki의 진화", meta: "G03A", hue: 190, skipGenerate: true,
        body: "The Graphify Blueprint — LLM Wiki의 진화." },
      { id: "g03b", title: "Graphify — LLM Wiki의 토큰 낭비를 줄이는 하이브리드 전처리", meta: "G03B", hue: 190, skipGenerate: true,
        body: "Graphify — LLM Wiki의 토큰 낭비를 줄이는 하이브리드 전처리." },
      { id: "g04", title: "LLM Wiki와 Graphify로 만드는 차세대 AI 세컨드 브레인", meta: "G04", hue: 190, skipGenerate: true,
        body: "LLM Wiki와 Graphify로 만드는 차세대 AI 세컨드 브레인." },
      { id: "g05", title: "NotebookLM + LLM Wiki + Obsidian로 분석 자료 저장 창고 구축하기", meta: "G05", hue: 190, skipGenerate: true,
        body: "NotebookLM + LLM Wiki + Obsidian로 분석 자료 저장 창고 구축하기." },
      { id: "g06a", title: "바이브코딩 및 PRD 작성 완벽 가이드", meta: "G06A", hue: 190, skipGenerate: true,
        body: "바이브코딩 및 PRD 작성 완벽 가이드." },
      { id: "g06b", title: "2026 바이브코딩 도구 비교 — Copilot, Claude Code, Cursor, Codex", meta: "G06B", hue: 190, skipGenerate: true,
        body: "2026 바이브코딩 도구 비교 — Copilot, Claude Code, Cursor, Codex." },
      { id: "g07", title: "Gemini와 Playwright 통합 — 지능형 웹 자동화 파이프라인", meta: "G07", hue: 190, skipGenerate: true,
        body: "Gemini와 Playwright 통합 — 지능형 웹 자동화 파이프라인." },
    ],
  },
  {
    id: "h00",
    folder: "H_Database",
    label: "데이터베이스",
    icon: "database",
    description: "DB 종류, Elasticsearch, 메타데이터, Qdrant, Supabase 등 데이터베이스 핵심 가이드.",
    items: [
      { id: "h01a", title: "개발자의 기본기 — 데이터베이스(DB)란 무엇인가", meta: "H01A", hue: 170, skipGenerate: true,
        body: "개발자의 기본기 — 데이터베이스(DB)란 무엇인가." },
      { id: "h01b", title: "Elastic Search란 무엇인가 — 정의, 구성요소, 장단점, 실습", meta: "H01B", hue: 170, skipGenerate: true,
        body: "Elastic Search란 무엇인가 — 정의, 구성요소, 장단점, 실습." },
      { id: "h01c", title: "메타데이터(Metadata) 완벽 정리 — 정의, 구성요소, 장단점, 실습", meta: "H01C", hue: 170, skipGenerate: true,
        body: "메타데이터(Metadata) 완벽 정리 — 정의, 구성요소, 장단점, 실습." },
      { id: "h01d", title: "Qdrant란 무엇인가 — 정의, 장단점, Docker 세팅, Python 실습", meta: "H01D", hue: 170, skipGenerate: true,
        body: "Qdrant란 무엇인가 — 정의, 장단점, Docker 세팅, Python 실습." },
      { id: "h02", title: "바이브 코딩을 위한 Supabase 완벽 가이드", meta: "H02", hue: 170, skipGenerate: true,
        body: "바이브 코딩을 위한 Supabase 완벽 가이드." },
    ],
  },
  {
    id: "i00",
    folder: "I_ML_DL",
    label: "ML/DL",
    icon: "code",
    description: "딥러닝·머신러닝 알고리즘과 개념을 하나씩 파헤치는 완벽 가이드 시리즈.",
    items: [
      { id: "i01", title: "딥러닝(Deep Learning)이란 무엇일까 — 정의, 원리, 모델 종류, ML·DL 차이점", meta: "I01", hue: 275, skipGenerate: true,
        body: "딥러닝(Deep Learning)이란 무엇일까 — 정의, 원리, 모델 종류, ML·DL 차이점." },
      { id: "i02", title: "ANN(인공신경망) 완벽 가이드 — 정의, 특징 및 장단점, 모델 학습 과정", meta: "I02", hue: 275, skipGenerate: true,
        body: "ANN(인공신경망) 완벽 가이드 — 정의, 특징 및 장단점, 모델 학습 과정." },
      { id: "i03", title: "CNN(합성곱 신경망) 완벽 가이드 — 정의, 특징 및 장단점, 모델 학습 과정", meta: "I03", hue: 275, skipGenerate: true,
        body: "CNN(합성곱 신경망) 완벽 가이드 — 정의, 특징 및 장단점, 모델 학습 과정." },
      { id: "i04", title: "RNN(순환 신경망) 완벽 가이드 — 정의, 특징 및 장단점, 모델 학습 과정", meta: "I04", hue: 275, skipGenerate: true,
        body: "RNN(순환 신경망) 완벽 가이드 — 정의, 특징 및 장단점, 모델 학습 과정." },
      { id: "i05", title: "Transformers(트랜스포머) 완벽 가이드 — 정의, 특징 및 장단점, 모델 학습 과정", meta: "I05", hue: 275, skipGenerate: true,
        body: "Transformers(트랜스포머) 완벽 가이드 — 정의, 특징 및 장단점, 모델 학습 과정." },
      { id: "i06", title: "로지스틱 회귀(Logistic Regression) 완벽 가이드", meta: "I06", hue: 275, skipGenerate: true,
        body: "로지스틱 회귀(Logistic Regression) 완벽 가이드." },
      { id: "i07", title: "KNN(K-Nearest Neighbors) 완벽 가이드", meta: "I07", hue: 275, skipGenerate: true,
        body: "KNN(K-Nearest Neighbors) 완벽 가이드." },
      { id: "i08", title: "나이브 베이즈(Naive Bayes) 완벽 가이드", meta: "I08", hue: 275, skipGenerate: true,
        body: "나이브 베이즈(Naive Bayes) 완벽 가이드." },
      { id: "i09", title: "SVM(Support Vector Machine) 완벽 가이드", meta: "I09", hue: 275, skipGenerate: true,
        body: "SVM(Support Vector Machine) 완벽 가이드." },
      { id: "i10", title: "의사결정 나무(Decision Tree) 완벽 가이드", meta: "I10", hue: 275, skipGenerate: true,
        body: "의사결정 나무(Decision Tree) 완벽 가이드." },
      { id: "i11", title: "Feature Engineering이란 — 정의 및 기법 정리", meta: "I11", hue: 275, skipGenerate: true,
        body: "Feature Engineering이란 — 정의 및 기법 정리." },
      { id: "i12", title: "랜덤 포레스트(Random Forest) 완벽 가이드", meta: "I12", hue: 275, skipGenerate: true,
        body: "랜덤 포레스트(Random Forest) 완벽 가이드." },
      { id: "i13", title: "Gradient Boosting(GBM) 완벽 가이드", meta: "I13", hue: 275, skipGenerate: true,
        body: "Gradient Boosting(GBM) 완벽 가이드." },
      { id: "i14", title: "XGBoost(eXtreme Gradient Boosting) 완벽 가이드", meta: "I14", hue: 275, skipGenerate: true,
        body: "XGBoost(eXtreme Gradient Boosting) 완벽 가이드." },
      { id: "i15", title: "LightGBM 완벽 가이드", meta: "I15", hue: 275, skipGenerate: true,
        body: "LightGBM 완벽 가이드." },
      { id: "i16", title: "CatBoost 완벽 가이드", meta: "I16", hue: 275, skipGenerate: true,
        body: "CatBoost 완벽 가이드." },
      { id: "i17", title: "머신러닝(Machine Learning)이란 무엇일까 — 통계적 기초와 데이터 엔지니어링의 정석", meta: "I17", hue: 275, skipGenerate: true,
        body: "머신러닝(Machine Learning)이란 무엇일까 — 통계적 기초와 데이터 엔지니어링의 정석." },
      { id: "i18", title: "지도 학습(Supervised Learning) 파헤쳐 보기", meta: "I18", hue: 275, skipGenerate: true,
        body: "지도 학습(Supervised Learning) 파헤쳐 보기." },
      { id: "i19", title: "비지도 학습(Unsupervised Learning) 파헤쳐 보기", meta: "I19", hue: 275, skipGenerate: true,
        body: "비지도 학습(Unsupervised Learning) 파헤쳐 보기." },
      { id: "i20", title: "준지도 학습(Semi-Supervised Learning) 파헤쳐 보기", meta: "I20", hue: 275, skipGenerate: true,
        body: "준지도 학습(Semi-Supervised Learning) 파헤쳐 보기." },
      { id: "i21", title: "강화 학습(Reinforcement Learning) 파헤쳐 보기", meta: "I21", hue: 275, skipGenerate: true,
        body: "강화 학습(Reinforcement Learning) 파헤쳐 보기." },
      { id: "i22", title: "YOLO(You Only Look Once) 완벽 가이드", meta: "I22", hue: 275, skipGenerate: true,
        body: "YOLO(You Only Look Once) 완벽 가이드." },
      { id: "i23", title: "데이터 라벨링(Data Labeling)이란 무엇인가", meta: "I23", hue: 275, skipGenerate: true,
        body: "데이터 라벨링(Data Labeling)이란 무엇인가." },
      { id: "i24", title: "하이퍼파라미터(Hyperparameter) 종류 완벽 정리", meta: "I24", hue: 275, skipGenerate: true,
        body: "하이퍼파라미터(Hyperparameter) 종류 완벽 정리." },
      { id: "i25", title: "하이퍼파라미터 튜닝(Hyperparameter Tuning) 완벽 가이드", meta: "I25", hue: 275, skipGenerate: true,
        body: "하이퍼파라미터 튜닝(Hyperparameter Tuning) 완벽 가이드." },
      { id: "i26", title: "Python Pickle이란 무엇일까 — 머신러닝 모델 저장·배포 가이드", meta: "I26", hue: 275, skipGenerate: true,
        body: "Python Pickle이란 무엇일까 — 머신러닝 모델 저장·배포 가이드." },
    ],
  },
  {
    id: "p00",
    folder: "P_IT_Tips",
    label: "IT_Tips",
    icon: "edit-3",
    description: "AX, MarkItDown, GPU/CPU/TPU/NPU, VS Code 단축키 등 알아두면 유용한 IT 상식 모음.",
    items: [
      { id: "p01", title: "AX(AI Transformation)란 무엇인가", meta: "P01", hue: 275, skipGenerate: true,
        body: "AX(AI Transformation)란 무엇인가." },
      { id: "p02", title: "MarkItDown이란 무엇인가", meta: "P02", hue: 275, skipGenerate: true,
        body: "MarkItDown이란 무엇인가." },
      { id: "p03", title: "GPU, CPU, TPU, NPU 완벽 비교", meta: "P03", hue: 275, skipGenerate: true,
        body: "GPU, CPU, TPU, NPU 완벽 비교." },
      { id: "p04", title: "VS Code 자주 쓰는 유용한 단축키 모음", meta: "P04", hue: 275, skipGenerate: true,
        body: "VS Code 자주 쓰는 유용한 단축키 모음." },
      { id: "p05", title: "MVP, PoC, Prototype, Pilot 완벽 비교", meta: "P05", hue: 275, skipGenerate: true,
        body: "MVP, PoC, Prototype, Pilot 완벽 비교." },
      { id: "p06", title: "NAS(Network Attached Storage)에 대해 자세히 알아보자", meta: "P06", hue: 275, skipGenerate: true,
        body: "NAS(Network Attached Storage)에 대해 자세히 알아보자." },
      { id: "p07", title: "Nested(중첩) 구조 완벽 가이드", meta: "P07", hue: 275, skipGenerate: true,
        body: "Nested(중첩) 구조 완벽 가이드." },
      { id: "p08", title: "npm, npx, yarn 완벽 가이드", meta: "P08", hue: 275, skipGenerate: true,
        body: "npm, npx, yarn 완벽 가이드." },
      { id: "p09", title: "Obsidian ↔ Notion 양방향 동기화 오픈소스, Im-Nobsidian 소개", meta: "P09", hue: 275, skipGenerate: true,
        body: "Obsidian ↔ Notion 양방향 동기화 오픈소스, Im-Nobsidian 소개." },
      { id: "p10", title: "RSS에 대해 자세히 알아보자", meta: "P10", hue: 275, skipGenerate: true,
        body: "RSS에 대해 자세히 알아보자." },
      { id: "p11", title: "RTK(Rust Token Killer) 완벽 가이드", meta: "P11", hue: 275, skipGenerate: true,
        body: "RTK(Rust Token Killer) 완벽 가이드." },
      { id: "p12", title: "SDK(Software Development Kit)에 대해 자세히 알아보자", meta: "P12", hue: 275, skipGenerate: true,
        body: "SDK(Software Development Kit)에 대해 자세히 알아보자." },
      { id: "p13", title: "Stack Overflow(스택 오버플로우)란 무엇일까", meta: "P13", hue: 275, skipGenerate: true,
        body: "Stack Overflow(스택 오버플로우)란 무엇일까." },
      { id: "p14", title: "SVN(Subversion) 완벽 가이드", meta: "P14", hue: 275, skipGenerate: true,
        body: "SVN(Subversion) 완벽 가이드." },
      { id: "p15", title: "Verification(검증)과 Validation(확인·타당성 검증)의 차이 완벽 정리", meta: "P15", hue: 275, skipGenerate: true,
        body: "Verification(검증)과 Validation(확인·타당성 검증)의 차이 완벽 정리." },
      { id: "p16", title: "Vibe Coding(바이브 코딩)에 대해 자세히 알아보자", meta: "P16", hue: 275, skipGenerate: true,
        body: "Vibe Coding(바이브 코딩)에 대해 자세히 알아보자." },
      { id: "p17", title: "동기/비동기 & 직렬/병렬 완벽 가이드", meta: "P17", hue: 275, skipGenerate: true,
        body: "동기/비동기 & 직렬/병렬 완벽 가이드." },
      { id: "p18", title: "사용자 인터페이스(UI)의 모든 것", meta: "P18", hue: 275, skipGenerate: true,
        body: "사용자 인터페이스(UI)의 모든 것." },
      { id: "p19", title: "채팅으로 맞춤형 Notion Template 자동 제작 AI Agent 소개, Notion Forge", meta: "P19", hue: 275, skipGenerate: true,
        body: "채팅으로 맞춤형 Notion Template 자동 제작 AI Agent 소개, Notion Forge." },
    ],
  },
  {
    id: "q00",
    folder: "Q_HTTP_ETC",
    label: "HTTP외",
    icon: "message-circle",
    description: "HTTP 외 전반적인 프로토콜 학습 자료를 모읍니다.",
    items: [
      { id: "q01", title: "API란 무엇일까 — API 정의, 종류, 설계, 개발 가이드", meta: "Q01", hue: 275, skipGenerate: true,
        body: "API란 무엇일까 — API 정의, 종류, 설계, 개발 가이드." },
      { id: "q02", title: "API 운영 가이드 — 보안, 성능, 테스트", meta: "Q02", hue: 275, skipGenerate: true,
        body: "API 운영 가이드 — 보안, 성능, 테스트." },
      { id: "q03", title: "API, 프로토콜, 소켓, JSON, gRPC 통신 스택 총정리", meta: "Q03", hue: 275, skipGenerate: true,
        body: "API, 프로토콜, 소켓, JSON, gRPC 통신 스택 총정리." },
      { id: "q04", title: "Beautiful Soup에 대해 자세히 알아보자", meta: "Q04", hue: 275, skipGenerate: true,
        body: "Beautiful Soup에 대해 자세히 알아보자." },
      { id: "q05", title: "HTTP 상태 코드 — 서버 오류와 리다이렉션 (5xx, 3xx)", meta: "Q05", hue: 275, skipGenerate: true,
        body: "HTTP 상태 코드 — 서버 오류와 리다이렉션 (5xx, 3xx)." },
      { id: "q06", title: "HTTP 상태 코드 — 클라이언트 오류 (4xx)", meta: "Q06", hue: 275, skipGenerate: true,
        body: "HTTP 상태 코드 — 클라이언트 오류 (4xx)." },
      { id: "q07", title: "JWT(JSON Web Token), Secret Key(시크릿 키) 완벽 가이드", meta: "Q07", hue: 275, skipGenerate: true,
        body: "JWT(JSON Web Token), Secret Key(시크릿 키) 완벽 가이드." },
      { id: "q08", title: "Prometheus(프로메테우스)에 대해 자세히 알아보자", meta: "Q08", hue: 275, skipGenerate: true,
        body: "Prometheus(프로메테우스)에 대해 자세히 알아보자." },
      { id: "q09", title: "Vite(비트)에 대해 자세히 알아보자", meta: "Q09", hue: 275, skipGenerate: true,
        body: "Vite(비트)에 대해 자세히 알아보자." },
      { id: "q10", title: "Node.js Role Complete Guide", meta: "Q10", hue: 275, skipGenerate: true,
        body: "Node.js Role Complete Guide." },
    ],
  },
  {
    id: "r00",
    folder: "R_Python",
    label: "Python",
    icon: "code",
    description: "Python Tool에 대해 심화 학습 자료를 모읍니다.",
    items: [
      { id: "r01", title: "uv 실전 가이드 — 프로젝트, 가상환경, 의존성 관리", meta: "R01", hue: 275, skipGenerate: true,
        body: "uv 실전 가이드 — 프로젝트, 가상환경, 의존성 관리." },
      { id: "r02", title: "venv, Conda, 그리고 uv", meta: "R02", hue: 275, skipGenerate: true,
        body: "venv, Conda, 그리고 uv." },
      { id: "r03", title: "파이썬 가상환경(venv) 사용하는 법 — 생성, 활성화, 삭제", meta: "R03", hue: 275, skipGenerate: true,
        body: "파이썬 가상환경(venv) 사용하는 법 — 생성, 활성화, 삭제." },
      { id: "r04", title: "Json-Repair — AI 시대의 망가진 JSON 자동 복구 라이브러리", meta: "R04", hue: 275, skipGenerate: true,
        body: "Json-Repair — AI 시대의 망가진 JSON 자동 복구 라이브러리." },
      { id: "r05", title: "pydantic이란 무엇인가", meta: "R05", hue: 275, skipGenerate: true,
        body: "pydantic이란 무엇인가." },
      { id: "r06", title: "Python Poetry에 대해 자세히 알아보자", meta: "R06", hue: 275, skipGenerate: true,
        body: "Python Poetry에 대해 자세히 알아보자." },
      { id: "r07", title: "뮤텍스(Mutex) vs 세마포어(Semaphore) 완벽 정리", meta: "R07", hue: 275, skipGenerate: true,
        body: "뮤텍스(Mutex) vs 세마포어(Semaphore) 완벽 정리." },
      { id: "r08", title: "온디바이스 AI(On-Device AI)에 대해 자세히 알아보자", meta: "R08", hue: 275, skipGenerate: true,
        body: "온디바이스 AI(On-Device AI)에 대해 자세히 알아보자." },
    ],
  },
  {
    id: "s00",
    folder: "S_Linux",
    label: "Linux",
    icon: "terminal",
    description: "Linux에 대해 이해하는 자료를 모읍니다.",
    items: [
      { id: "s01", title: "리눅스 관리자의 기본 — 패키지 설치와 관리", meta: "S01", hue: 275, skipGenerate: true,
        body: "리눅스 관리자의 기본 — 패키지 설치와 관리." },
      { id: "s02", title: "리눅스 네트워크와 원격 접속", meta: "S02", hue: 275, skipGenerate: true,
        body: "리눅스 네트워크와 원격 접속." },
      { id: "s03", title: "리눅스 명령어 — 파일과 디렉토리 탐색·관리", meta: "S03", hue: 275, skipGenerate: true,
        body: "리눅스 명령어 — 파일과 디렉토리 탐색·관리." },
      { id: "s04", title: "리눅스 시스템 정보 및 프로세스 관리", meta: "S04", hue: 275, skipGenerate: true,
        body: "리눅스 시스템 정보 및 프로세스 관리." },
      { id: "s05", title: "리눅스 활용 꿀팁 — 압축, 반복, 그리고 자동화", meta: "S05", hue: 275, skipGenerate: true,
        body: "리눅스 활용 꿀팁 — 압축, 반복, 그리고 자동화." },
      { id: "s06", title: "screen 사용법 A to Z — 정의, 설치, 명령어 총정리", meta: "S06", hue: 275, skipGenerate: true,
        body: "screen 사용법 A to Z — 정의, 설치, 명령어 총정리." },
      { id: "s07", title: "우분투(Ubuntu)에서 구글 드라이브 연동 및 사용 완벽 가이드", meta: "S07", hue: 275, skipGenerate: true,
        body: "우분투(Ubuntu)에서 구글 드라이브 연동 및 사용 완벽 가이드." },
    ],
  },
  {
    id: "t00",
    folder: "T_Git_and_Github",
    label: "Git_and_Github",
    icon: "terminal",
    description: "Python, Linux, Git, Node.js 등 개발/인프라 기초 기술을 정리합니다.",
    items: [
      { id: "t01", title: "CI/CD(지속적 통합·지속적 배포) 완벽 정복 가이드", meta: "T01", hue: 230, skipGenerate: true,
        body: "CI/CD(지속적 통합·지속적 배포) 완벽 정복 가이드." },
      { id: "t02", title: "Git Flow vs GitHub Flow 완전 비교 가이드", meta: "T02", hue: 230, skipGenerate: true,
        body: "Git Flow vs GitHub Flow 완전 비교 가이드." },
      { id: "t03", title: "GitHub Actions 완벽 정복 가이드 — 코드 푸시부터 자동 배포까지 한 번에", meta: "T03", hue: 230, skipGenerate: true,
        body: "GitHub Actions 완벽 정복 가이드 — 코드 푸시부터 자동 배포까지 한 번에." },
      { id: "t04", title: "GitHub Pull Request부터 Merge까지 — 코드 리뷰의 모든 것", meta: "T04", hue: 230, skipGenerate: true,
        body: "GitHub Pull Request부터 Merge까지 — 코드 리뷰의 모든 것." },
      { id: "t05", title: "GitHub 100MB 이상 대용량 파일 업로드 완벽 가이드 (Git LFS)", meta: "T05", hue: 230, skipGenerate: true,
        body: "GitHub 100MB 이상 대용량 파일 업로드 완벽 가이드 (Git LFS)." },
      { id: "t06", title: "GitLab Merge Request 완벽 가이드 — Issue 연동부터 코드 리뷰까지", meta: "T06", hue: 230, skipGenerate: true,
        body: "GitLab Merge Request 완벽 가이드 — Issue 연동부터 코드 리뷰까지." },
      { id: "t07", title: "GitHub 로그인 계정 확인 및 변경 방법", meta: "T07", hue: 230, skipGenerate: true,
        body: "GitHub 로그인 계정 확인 및 변경 방법." },
      { id: "t08", title: "원격 저장소 연결 및 관리 (git remote)", meta: "T08", hue: 230, skipGenerate: true,
        body: "원격 저장소 연결 및 관리 (git remote)." },
      { id: "t09", title: "Git 브랜치(Branch) 핵심 가이드", meta: "T09", hue: 230, skipGenerate: true,
        body: "Git 브랜치(Branch) 핵심 가이드." },
      { id: "t10", title: "GitHub Copilot SDK 완전 정복 가이드 — Copilot을 API처럼 내 서비스에 연동하는 방법", meta: "T10", hue: 230, skipGenerate: true,
        body: "GitHub Copilot SDK 완전 정복 가이드 — Copilot을 API처럼 내 서비스에 연동하는 방법." },
    ],
  },
  {
    id: "v00",
    folder: "V_Bookmarks",
    label: "북마크 · 즐겨찾기",
    icon: "bookmark",
    description: "나중에 다시 볼 만한 링크·아티클과, 자주 찾는 고정 항목을 함께 모아둡니다.",
    items: [
      { id: "bm-1", title: "디자인 레퍼런스 모음", meta: "링크 12개", hue: 340,
        body: "UI/UX 작업 시 참고하는 웹사이트와 갤러리 링크 모음입니다.\n\n주기적으로 새 레퍼런스를 추가하고 있습니다." },
      { id: "bm-2", title: "개발자 블로그 모음", meta: "링크 8개", hue: 340,
        body: "팀에서 자주 참고하는 기술 블로그 목록입니다.\n\n프론트엔드, 백엔드, 인프라 카테고리로 분류되어 있습니다." },
      { id: "bm-3", title: "뉴스레터 아카이브", meta: "이슈 20개", hue: 340,
        body: "구독 중인 업계 뉴스레터 중 다시 보고 싶은 이슈를 모아둔 아카이브입니다." },
      { id: "bm-4", title: "툴 비교 아티클", meta: "링크 6개", hue: 340,
        body: "생산성 도구, 협업 툴을 비교 분석한 아티클 모음입니다.\n\n툴 도입을 검토할 때 참고합니다." },
      { id: "bm-5", title: "자주 쓰는 템플릿", meta: "고정됨", hue: 45,
        body: "매번 새로 만들지 않고 재사용하는 문서/기획 템플릿 모음입니다." },
      { id: "bm-6", title: "핵심 대시보드 링크", meta: "고정됨", hue: 45,
        body: "업무에 자주 쓰는 대시보드 바로가기 링크 모음입니다." },
      { id: "bm-7", title: "즐겨 찾는 문서", meta: "고정됨", hue: 45,
        body: "가장 자주 열어보는 문서 모음입니다." },
      { id: "bm-8", title: "자주 쓰는 도구", meta: "고정됨", hue: 45,
        body: "업무에서 매일 사용하는 도구와 바로가기 목록입니다." },
    ],
  },
];

// Node/CommonJS export (used by generate_items.js).
if (typeof module !== "undefined") {
  module.exports = { CATEGORIES, PORTAL_TOOLS };
}
